// Placeholder for generated Firebase options.
// Replace with actual `firebase_options.dart` generated by FlutterFire CLI.
class FirebaseOptionsPlaceholder {
  static const String apiKey = 'API_KEY_GOES_HERE';
  static const String projectId = 'PROJECT_ID_GOES_HERE';
}
